### ISSUE TITLE
Jar CLI mode does not work with Python 3

### ISSUE THREAD

**Issue by scop** [peterbe/django-html-validator#12]
Blows up in

```python
        err = unicode(err, 'utf-8')
```

<code>name 'unicode' is not defined</code>

**Comment by peterbe** [comment]
Oh. I think that needs some `six` love. Wanna write a patch?

**Comment by scop** [comment]
I hope this can be done without <code>six</code>. Maybe PR #14 works for both py 2 and 3? It seems to work for 3, haven't tested (nor going to) test with 2.

**Comment by scop** [comment]
Fixed in 171ca927e33301a8c804bd0501e6b8bad19a430e
