### ISSUE TITLE
No such file or directory README

### ISSUE THREAD

**Issue by Colleoni** [peterbe/django-html-validator#2]
Hi thanks for your useful application.

However, I have an error when I am trying to install it:

IOError: [Errno 2] No such file or directory: .... build/django-html-validator/README.md'

I google it and I think that happens because you miss the MANIFEST.in file... but I am not sure

**Comment by peterbe** [comment]
Fixed now.

**Comment by Colleoni** [comment]
Thanks

**Comment by scop** [comment]
Pypi still has version 0.3 which doesn't contain this fix, so "pip install django-html-validator" fails with this error.

**Comment by peterbe** [comment]
Thanks for reminding me https://pypi.python.org/pypi/django-html-validator/0.3.1
